description: UPF3 - Mid Point 2

pfcp:
  addr: upf3.free5gc.org
  nodeID: upf3.free5gc.org

gtpu:
  forwarder: gtp5g
  ifList:
    - addr: upf3.free5gc.org
      type: N9

dnnList:
  - dnn: urllc
    cidr: 10.72.0.0/16
