version: 1.0.3
description: UPF4 - URLLC Server-Side

pfcp:
  addr: upf4.free5gc.org
  nodeID: upf4.free5gc.org

gtpu:
  forwarder: gtp5g
  ifList:
    - addr: upf4.free5gc.org
      type: N9

dnnList:
  - dnn: urllc
    cidr: 10.83.0.0/16

logger:
  enable: true
  level: info
  reportCaller: false
