version: 1.0.3
description: UPF2 - Intermediate

pfcp:
  addr: upf2.free5gc.org
  nodeID: upf2.free5gc.org

gtpu:
  forwarder: gtp5g
  ifList:
    - addr: upf2.free5gc.org
      type: N9

dnnList:
  - dnn: urllc
    cidr: 10.81.0.0/16

logger:
  enable: true
  level: info
  reportCaller: false
