description: UPF2 - Mid Point 1

pfcp:
  addr: upf2.free5gc.org
  nodeID: upf2.free5gc.org

gtpu:
  forwarder: gtp5g
  ifList:
    - addr: upf2.free5gc.org
      type: N9

dnnList:
  - dnn: urllc
    cidr: 10.71.0.0/16
