version: 1.0.3
description: UPF1 - gNB Entry Point

pfcp:
  addr: upf1.free5gc.org
  nodeID: upf1.free5gc.org

gtpu:
  forwarder: gtp5g
  ifList:
    - addr: upf1.free5gc.org
      type: N3

dnnList:
  - dnn: urllc
    cidr: 10.80.0.0/16

logger:
  enable: true
  level: info
  reportCaller: false
