description: UPF1 - Entry Point

pfcp:
  addr: upf1.free5gc.org
  nodeID: upf1.free5gc.org

gtpu:
  forwarder: gtp5g
  ifList:
    - addr: upf1.free5gc.org
      type: N3

dnnList:
  - dnn: urllc
    cidr: 10.70.0.0/16
